name: Deploy on Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy on Prod by @${{ github.actor }}
    runs-on: ubuntu-latest
    env:
      REPO_NAME: tripbox-frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Project
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".,!.git,!.github,!tests,!.gitignore,!.nuxt,!node_modules"
          target: /var/sites/${{ env.REPO_NAME }}
          rm: true

      - name: Update Project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /var/sites/${{ env.REPO_NAME }}
            cd ../infra
            docker compose up -d --build ${{ env.REPO_NAME }}

      - name: Slack Notification On Success
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: ${{ vars.SLACK_CHANNEL }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: "Deployed by ${{ github.actor }}"
